services:
  api:
    build:
      context: ./stock-control-api
    ports:
      - "8080:8080"

  web:
    build:
      context: ./stock-control-web
      args:
        VITE_API_BASE_URL: http://localhost:8080/api
    ports:
      - "5173:80"
    depends_on:
      - api
